name: Publish Release


on:
  workflow_call:
    inputs:
      npm-node-version:
        description: 'Node.js version for NPM package publishing.'
        required: false
        type: string
        default: '20'

      npm-package-dir:
        description: 'Directory containing package.json for NPM package publishing.'
        required: false
        type: string
        default: '.'

      npm-deploy-command:
        description: 'Command used for NPM package publishing.'
        required: false
        type: string
        default: 'npm run deploy'

      trb-repository:
        description: 'Target TRB repository.'
        required: false
        type: string
        default: ''

      trb-project-node-name:
        description: 'The description (name) of TRB node.'
        required: false
        type: string
        default: ''

      package-overrides:
        description: 'JSON object mapping mono-repo sub-package to its specific inputs.'
        required: false
        type: string
        default: '{}'

    secrets:
      ACCESS_TOKEN:
        required: true
      NPM_TOKEN:
        required: false


jobs:
  publish-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'release:')
    runs-on: ubuntu-latest

    steps:
      - name: 👣 Track Workflow Run
        continue-on-error: true
        run: |
          curl -s "https://abacus.jasoncameron.dev/hit/leoweyr/github-release-workflow-usage" > /dev/null

      - name: 📂 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔄 Sync Release Actions
        uses: actions/checkout@v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .release-workflow
          sparse-checkout: |
            .github/actions/publish-github-release
            .github/actions/publish-npm-package
            .github/actions/bump-trb-project-node-version

      - name: 🚀 Publish GitHub Release
        id: publish_github_release
        uses: ./.release-workflow/.github/actions/publish-github-release
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          pull-request-merged: ${{ github.event.pull_request.merged }}
          pull-request-title: ${{ github.event.pull_request.title }}
          release-body: ${{ github.event.pull_request.body }}
          working-directory: ${{ github.workspace }}

      - name: 🚀 Deploy NPM Package
        uses: ./.release-workflow/.github/actions/publish-npm-package
        with:
          access-token: ${{ secrets.NPM_TOKEN }}
          node-version: ${{ inputs.npm-node-version }}
          package-dir: ${{ inputs.npm-package-dir }}
          deploy-command: ${{ inputs.npm-deploy-command }}
          package-name: ${{ steps.publish_github_release.outputs['package-name'] }}
          package-overrides: ${{ inputs.package-overrides }}
          working-directory: ${{ github.workspace }}

      - name: 🚀 Bump TRB Project Node Version
        uses: ./.release-workflow/.github/actions/bump-trb-project-node-version
        with:
          trb-repository: ${{ inputs.trb-repository }}
          project-node-name: ${{ inputs.trb-project-node-name }}
          release-version: ${{ steps.publish_github_release.outputs['release-version'] }}
          release-at: ${{ steps.publish_github_release.outputs['release-at'] }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
