name: Publish Release

on:
  workflow_call:
    inputs:
      npm-node-version:
        description: 'Node.js version for npm publish.'
        required: false
        type: string
        default: '20'
      npm-package-dir:
        description: 'Directory containing package.json for npm publish.'
        required: false
        type: string
        default: '.'
      npm-deploy-command:
        description: 'Command used to publish npm package.'
        required: false
        type: string
        default: 'npm run deploy'
    secrets:
      ACCESS_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  publish-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'release:')
    runs-on: ubuntu-latest

    steps:
      - name: 👣 Track Workflow Run
        continue-on-error: true
        run: |
          curl -s "https://abacus.jasoncameron.dev/hit/leoweyr/github-release-workflow-usage" > /dev/null

      - name: 📂 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Verify Release Tag Name
        id: extract_tag
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          TAG_NAME=$(echo "$TITLE" | sed 's/release: //')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          VERSION_TITLE=${TAG_NAME#v}
          echo "VERSION_TITLE=$VERSION_TITLE" >> $GITHUB_ENV

      - name: 📝 Create Release Body File
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: echo "$PR_BODY" > release_body.md

      - name: 🚀 Deploy GitHub Release
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          gh release create ${{ env.TAG_NAME }} \
            --title "${{ env.VERSION_TITLE }}" \
            --notes-file release_body.md \
            --verify-tag

      - name: 🔍 Verify NPM Token
        id: verify_npm_token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo '👻 NPM_TOKEN is not configured.'
            printf 'enabled=false\n' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          printf 'enabled=true\n' >> "$GITHUB_OUTPUT"

      - name: 🔄 Sync NPM Publish Action
        if: steps.verify_npm_token.outputs.enabled == 'true'
        uses: actions/checkout@v4
        with:
          repository: 'leoweyr/github-release-workflow'
          path: .release-workflow
          sparse-checkout: .github/actions/npm-publish

      - name: 🚀 Deploy NPM Package
        if: steps.verify_npm_token.outputs.enabled == 'true'
        uses: ./.release-workflow/.github/actions/npm-publish
        with:
          node-version: ${{ inputs.npm-node-version }}
          package-dir: ${{ inputs.npm-package-dir }}
          deploy-command: ${{ inputs.npm-deploy-command }}
          access-token: ${{ secrets.NPM_TOKEN }}
