name: Prepare Release


on:
  workflow_call:
    inputs:
      node-verions:
        description: 'Node.js version to use.'
        required: false
        type: string
        default: '20'

      commit-user-name:
        description: 'Git user name for commit'
        required: false
        type: string
        default: 'github-actions[bot]'

      commit-user-email:
        description: 'Git user email for commit.'
        required: false
        type: string
        default: 'github-actions[bot]@users.noreply.github.com'

      packages:
        description: 'JSON object mapping mono-repo sub-package name to its workspace directory.'
        required: false
        type: string
        default: '{}'

    secrets:
      ACCESS_TOKEN:
        required: true
        description: 'GitHub Token for authentication.'


jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: 👣 Track Workflow Run
        continue-on-error: true
        run: |
          curl -s "https://abacus.jasoncameron.dev/hit/leoweyr/github-release-workflow-usage" > /dev/null

      - name: 📂 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔄 Sync Release Action
        uses: actions/checkout@v4
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: .release-workflow
          sparse-checkout: |
            .github/actions/prepare-release
            src/cliff.toml

      - name: 📦 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-verions }}

      - name: 🧰 Prepare Release
        uses: ./.release-workflow/.github/actions/prepare-release
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          tag-name: ${{ github.ref_name }}
          commit-user-name: ${{ inputs.commit-user-name }}
          commit-user-email: ${{ inputs.commit-user-email }}
          packages: ${{ inputs.packages }}
          changelog-configuration-path: .release-workflow/src/cliff.toml
          working-directory: ${{ github.workspace }}
